version: '2'
services:
  jenkins:
    image: docker.io/bitnami/jenkins:latest
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    ports:
      - '9081:22'
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHKPJYf7x9j+rkzjmdSBOCP1HGoSTKCJ50aSeiJ4XGRQTzHvVVWv3mt6eakux7IKrVbipJ9iIZPKYUrgcX1VJLWgJhskPMtz/pkKnwmmJsqc6yqB7RQmlf9jSmxfzbVWVAS+d1bQFnktp4l1djQEnI/aUTAXuXfwwy7pUqIJDO2Cc89qgp1lXrLXnwwc3XSvj0xdynEaQ+wNCjGZz2iwZ8doSOCGVTm6hbrlPykqAurdwbu4a9mDzKamH1cGzTMRFVZM7UoejOKQOdUl3tR7EzdnLlrz9F47e69MsfrDwNnJ6SUkkv6GJGY871R1lOkivKdWXJTZwrFVGAceGZAGgbbN/Pm8ET1YvMlwob+LjzwMS6J/ouFJ98fs68c3huTmvn6WjBb4pTvRMAj57k/1jwB0rzF2gykywdqbJmAgbRtYRdz7y9+rxaoVAF5Eh2ZdY49vdc6MNFkd8i9PD+67YQmAbehz+ONr9ALKjqrmnKTaWwbYBtq/Hndpw+VvnXni0= root@aaf5f781875a
volumes:
  jenkins_data:
    driver: local
